import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
	return (
		<main>
			<Head>
				<title>Świadomość</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="../assets/svg/logo.svg" />
			</Head>
		</main>
	);
};

export default Home;
