import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/About.module.scss';

const Home: NextPage = () => {
	return (
		<main className={styles.main}>
			<Head>
				<title>Świadomość</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<section className={styles.hero}>
				<Image
					src="/hero.jpg"
					layout="fill"
					objectFit="cover"
					className={styles.image}
				/>
				<a href="#beginning" className={styles.scrollBtn}>
					V
				</a>
			</section>
			<section id="beginning" className={styles['two-column']}>
				<h1>Kim Jesteśmy?</h1>
				<div className={styles['two-column-layer1']}>
					<article>
						The more we do this - the more it will do good things to our heart.
						Exercising the imagination, experimenting with talents, being
						creative; these things, to me, are truly the windows to your soul.
						That&#39;s crazy. You don&#39;t have to spend all your time thinking
						about what you&#39;re doing, you just let it happen. Son of a gun.
						That&#39;s crazy. If you&#39;ve been in Alaska less than a year
						you&#39;re a Cheechako. I really believe that if you practice enough
						you could paint the &#39;Mona Lisa&#39; with a two-inch brush.
						It&#39;s cold, but it&#39;s beautiful. The secret to doing anything
						is believing that you can do it. Anything that you believe you can
						do strong enough, you can do. Anything. As long as you believe.
					</article>
					<div className={styles['two-column-layer2']}>
						<h2>Nasze wartości</h2>
						<ol className={styles['two-column-list']}>
							<li>Use absolutely no pressure.</li>
							<li>We don&#39;t have to be concerned about it.</li>
							<li>
								We&#39;ll have a super time. Let&#39;s make a nice big leafy
								tree.
							</li>
							<li>
								We don&#39;t really know where this goes - and I&#39;m not sure
								we really care.
							</li>
						</ol>
					</div>
				</div>
			</section>
		</main>
	);
};

export default Home;
